import { StyleSheet } from 'react-native';

import { typography } from '@/constants/typography';
import { borderRadius, layout } from '@/constants/spacing';

export function createFacialStyles(colors: any, insetBottom: number) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.bgPrimary },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: layout.screenPadding,
      height: layout.headerHeight,
      gap: 12,
    },
    backButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
    headerTitle: { ...typography.headlineMedium, color: colors.textPrimary },
    scrollView: { flex: 1 },
    scrollContent: { paddingHorizontal: layout.screenPadding, paddingBottom: 24 },
    sectionTitle: { ...typography.labelLarge, color: colors.textPrimary, marginBottom: 10 },
    hint: { marginTop: 8, ...typography.caption, color: colors.textTertiary },
    row: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingRight: 6 },
    hairRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingRight: 6 },
    wrapRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 10 },
    gridWrap: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    squareTileWrap: { width: '31%' },
    squareTile: {
      width: '100%',
      aspectRatio: 1,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgSecondary,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      paddingHorizontal: 6,
      paddingVertical: 8,
    },
    squareTileActive: { borderColor: colors.accent, backgroundColor: colors.accentMuted },
    squareTileSwatch: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: colors.border,
    },
    squareTileText: { ...typography.caption, color: colors.textSecondary, textAlign: 'center' },
    squareTileTextActive: { color: colors.textPrimary },
    chip: {
      width: 64,
      height: 64,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgSecondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chipActive: { borderColor: colors.accent, backgroundColor: colors.accentMuted },
    chipLabel: { ...typography.caption, color: colors.textSecondary, marginTop: 4 },
    hairCardWrap: { width: 96, marginRight: 10 },
    hairCardWrapGrid: { width: '31%', marginRight: 0 },
    hairCard: {
      width: '100%',
      aspectRatio: 0.78,
      borderRadius: 16,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.bgSecondary,
    },
    hairCardActive: { borderColor: colors.accent, borderWidth: 2 },
    hairCardLabel: { ...typography.caption, color: colors.textSecondary, marginTop: 6, textAlign: 'center' },
    hairFallback: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.bgSecondary,
      gap: 4,
    },
    hairFallbackText: { ...typography.caption, color: colors.textSecondary },
    colorChip: {
      borderRadius: borderRadius.full,
      backgroundColor: colors.bgSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingVertical: 9,
      paddingHorizontal: 13,
      marginRight: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    colorChipWrapItem: { marginRight: 0 },
    colorChipActive: { borderColor: colors.accent, backgroundColor: colors.bgCard },
    colorDot: {
      width: 14,
      height: 14,
      borderRadius: 7,
      borderWidth: 1,
      borderColor: colors.border,
    },
    colorChipText: { ...typography.caption, color: colors.textSecondary },
    colorChipTextActive: { color: colors.textPrimary },
    focusedOverlay: {
      position: 'absolute',
      top: layout.headerHeight,
      left: 0,
      right: 0,
      bottom: insetBottom + layout.tabBarHeight + 4,
      backgroundColor: colors.bgPrimary,
      zIndex: 20,
      paddingHorizontal: layout.screenPadding,
      paddingTop: 12,
    },
    focusedHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
    focusedTitle: { ...typography.labelLarge, color: colors.textPrimary },
    shrinkButton: {
      paddingHorizontal: 10,
      paddingVertical: 8,
      marginRight: -10,
    },
    bottomBar: {
      backgroundColor: colors.bgPrimary,
      paddingHorizontal: layout.screenPadding,
      paddingTop: 12,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
    },
  });
}
